name: Deploy To Server

on:
  # Deploy on merge to main
  push:
    branches: [ develop, main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

#  # Manually deploy branch
#  workflow_dispatch:
#    branches: [ main ]

jobs:
  deploy:
    name: Capistrano Deploy to Staging Server
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key to Server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github_actions
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'
          config: |
            host property.aasatech.asia
              IdentityFile ~/.ssh/github_actions
              IdentitiesOnly yes
              ForwardAgent yes
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}

      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true

      - name: Deploy to staging
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github_actions
          bundle exec cap staging deploy
